layout_spectrum: 0.8021277
name: Fox Approach
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.9569985
  lightness: 0.1808511
  saturation: 0.3446808
  rhythmicContrast: 0.8042553
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.8659574
